### ISSUE TITLE
設計／修正箇所の検討のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#11]
まず「設計／修正箇所の検討」ステップにおける、そもそもの課題を具体的にする。

**Comment by shintykt** [comment]
課題
- 設計想定を誤り、実装開始時点で方向性を間違える可能性がある
- 作業中にAPIが必要だったことがわかり、API完成まで作業ストップ、その分スケジュール遅延
- チケット起票時にFE/BE側のタスクをそれぞれ洗い出すのがいいが、どのように洗い出すのかをナレッジ化
- 実装したことがないと設計/修正箇所は困難

対策
- ①PM：新メンバーをアサインする際は設計/修正箇所のヒントを提示
- ②PM&エンジニア：まずは実装で必要そうなタスクをネットなどで調べながら洗い出し、不確定要素のあるタスクについて調査・サンプル開発などによりリスクを潰す

ガイドラインへのまとめ方
- 対策②について掘り下げてまとめる
  - 新しく入ったメンバーに観点をもらいながらまとめるのが良さそう
