### ISSUE TITLE
ビルドのたたき台設定

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#12]
**課題**

ビルドに失敗するなど環境構築で時間が溶けるときがある。

**解決策**

検討が必要

**Comment by ymmtshny** [comment]
バックエンド、Webフロントは必ずDocker使う。
スマホアプリで、Docker使うのは微妙かも。

**Comment by shintykt** [comment]
つまづくポイント
- フロント
  - 開発環境のバージョンがPJごとに差があってビルドに失敗することがある
    - Flutterバージョン
    - Dartバージョン
    - 各種pubバージョン
    - CocoaPodsバージョン
  - Firebase周りの設定でビルドが通らない
    - Xcodeのライブラリ依存関係がVSCodeに反映されない=>XcodeでビルドしてからVSCodeでビルド
- バック
  - macOSなどの環境起因でDockerが立ち上がらないことはある
  - ライセンスコード、APIキーの不具合（サービス元の不具合）でビルドが通らない

対策
- ケースバイケースがほとんどなので、ビルドできなった事例を溜めていく
- 並行して一人で抱え込みすぎないように質問しやすい環境づくりを進める

ガイドラインへのまとめ方
- よくあるつまづくポイント
- つまづいた時の質問ルール
- ナレッジ蓄積のためのルール

**Comment by nambaseiichi-pentagon** [comment]
バックエンド
* docker化しないほうが開発早い場合もある
