### ISSUE TITLE
ブランチ作成のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#13]
**現状**

ブランチ名がバラバラ、法則性がない→ルールが浸透していない

ブランチ名がバラバラであることによる、開発品質の低下があるのか？議論。

**Comment by shintykt** [comment]
感触
- develop（デフォルト）、staging、productionに分ける？mainは不要？運用ルールが必要
- developからの派生ブランチ（チケット対応ブランチ）のブランチ名はチケット名に合わせる
- 緊急対応チケットはstagingからブランチを生やす（対応後にproduction、developにマージ）
