### ISSUE TITLE
動作確認のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#15]
**課題**
ジュニアエンジニアが、バグ発生時に調べ方がわからない

**やること**
バグ解消についてのチップスをまとめる。

**Comment by ymmtshny** [comment]
- 再現するかどうか
- 原因を考える
- 原因の切り分けをする
- 仮説検証をする
- 修正案を考える
- 修正案の影響範囲を考える
- 自動テストを実施する
- 手動テストを実施する

**Comment by nambaseiichi-pentagon** [comment]
今日PR＆完了予定
