### ISSUE TITLE
プルリクエスト作成のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#16]
**課題**

結合テスト時に出てくるバグの量が想定より多い
→ プルリクエスト時に、レビューをしているが、バグが紛れ込む
→ プルリクエスト時のレビューの精度が低い
→ レビューワーがどこまでレビューしたら良いのか明確になっていない
（期待値と背景がないと、何をレビューしたらいいかわからないとの声がある）

**対策**

- プルリクエスト作成時のルールを定義する
- プルリクエスト作成時に記述する項目を明確にする
- プルリクエストのテンプレートを記載する

**Comment by shintykt** [comment]
https://github.com/pentagon-tokyo/ptg-quality/pull/38
で対応済みのためクローズ
