### ISSUE TITLE
ソースコード確認のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#20]
品質向上のための課題が何か議論する

**Comment by shintykt** [comment]
課題（後で追加予定）
- そもそものコード品質を上げるには？
- （ガイドラインの）コーディングのセクションの内容を定着させる
- レビュー指摘リストの充実=>横展開
- コード品質を保つための具体的な観点整理
  - BE
    - DB操作などなど
  - FE
    - nullチェックなどなど

**Comment by shintykt** [comment]
https://github.com/pentagon-tokyo/ptg-quality/pull/68
で対応済みのためクローズ
