### ISSUE TITLE
関連箇所のチェックのたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#21]
**課題**

関連箇所のチェックをやっている人とやっていない人がいる？
あまり時間ないとコード部分だけのチェックになってしまう

**対策**
画面実装の場合は前後の結合の確認、内部・リファクタリング等の実装は関連する箇所を確認し、エビデンス動画を載せることでレビューワーの確認コストを減らすようにする。

**Comment by shintykt** [comment]
https://github.com/pentagon-tokyo/ptg-quality/pull/38
で対応済みのためクローズ
