### ISSUE TITLE
動作確認のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#22]
**課題**

ブランチをPullしてローカルでデバッグ（動作確認）をしていない。コードだけレビューしている場合がある
=> バグの発生に気が付かない可能性がある

**対策**

- 期待値に即した動作確認を行う
- レビュワーのチェックリストがあれば良い

**Comment by shintykt** [comment]
https://github.com/pentagon-tokyo/ptg-quality/pull/38
で対応済みのためクローズ
