### ISSUE TITLE
マージのたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#24]
**課題**
レビューアがマージ／レビュー依頼に気づかないので、遅延につながる

**解決策**
マージ・PRの際はチャットで報告orメンションして連絡する

**Comment by ymmtshny** [comment]
- 誰がマージすべきか
- いつマージして良いのか
- マージ後、何をすれば良いのか

**Comment by nambaseiichi-pentagon** [comment]
* マージは実装者が行う
* マージ報告も実装者が行う
* マージ後、チケットを完了にする（新規開発の場合）
* マージ後、チケットをデプロイ待ちにする（バグ改修の場合）
