### ISSUE TITLE
実績工数入力のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#25]
何が課題か議論

**Comment by shintykt** [comment]
課題
- 計画工数（見積もり）の差分を管理したい
  - 計画工数にはどんな作業を含める？実装？レビューも？
  - レビュー工数はどう見積もるか？一律？実装工数に応じて増やす？
- 差分が大きい場合などにその原因を特定するきっかけにしたい
- これらをもって見積もりの精度（スコープ、タスク整理など）を高めたい
- 見積もりの精度を高めるための知見をチームのナレッジにしたい
