### ISSUE TITLE
チケット作成のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#29]
**課題**

テスト時に、チケットを細かく区切る/新たなバグが発生する
→周辺確認でバグ発見した際、チケット分割すべきか、同チケット内で対応すべきかがわからないとの声
=> バグ解消のためのチケットの作成方法がわからない

**解決策**
軽微な修正であれば同チケットで対応、新たなバグが発生した際に親課題を設定し、チケット内でバグを細かく報告する

**Comment by nambaseiichi-pentagon** [comment]
7/18中にレビュー依頼出す予定（小寺さん）
