### ISSUE TITLE
チケットクローズのたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#30]
バックログで誰がチケットクローズするべきか
=> チケット作成者をアサインし、制作者が確認の上クローズするのが良いと思われる。

**Comment by nambaseiichi-pentagon** [comment]
運用例

* チケット完了したら担当者がチケット起票者に戻し、起票者がクローズする

**Comment by shintykt** [comment]
以下の運用で決定

- 新規開発（〜結合テストまで）
  - チケット担当がテストして問題なければチケットのステータスを「完了」にして、チケットをクローズする
- 新規開発（結合テスト以降）＆運用保守
  - チケット完了したらチケットのステータスを「テスト待ち」にして、チケット担当を起票者に設定する
  - 起票者がテストして問題なければチケットのステータスを「完了」にして、チケットをクローズする
