### ISSUE TITLE
チケット仕様確認についてたたき台を作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#5]
**課題**

仕様に関する不明点などについてのやり取りをどこでやるかが決まっていない
＊仕様も開発だけor開発+デザイナーで話す内容がある"

=> 決まってないことの何が課題なのか社内で確認する

**Comment by shintykt** [comment]
課題
- コミュケーションルール
  - やり取りの場所が問題でなく、発信が相手に届いていないことが問題？
  - 後から情報を追いづらい
- チケット対応方法
  - チケットアサインされた後
    - 要件がわからなった時
      - PM側のアサインの問題
      - PM側のチケット記載内容の問題・・・A
      - 要件に不確実要素がある・・・B
    - 要件はわかるが、開発仕様がわからなった時
      - 開発仕様に不確実要素がある・・・C

対策
- コミュケーションルール
  - figma、backlog、githubでコメントした後にmattermostでもメンション飛ばす
    - 議論については極論相手に伝わればOK
  - 後で情報追えるように決まったことはbacklogに集約する
- チケット対応方法
  - 課題A=>作成中のチケットテンプレートを活用する
  - 課題BC=>不確実要素に対する行動方針をまとめる

**Comment by nambaseiichi-pentagon** [comment]
課題
* 多くのタスクを抱えている（同時並行で対応している）と、backlogでのやり取りに統一されている方がわかりやすい
    * チャットでやりとりすると議論がどこまで進んだか把握しづらくなる
* PMがプロジェクト途中参加＆プロジェクト関係者多いとき、（仕様などの）確認が必要となるケースがあり、backlogの方がわかりやすい
    * 仕様確認が必要なとき、お客様をアサイン
    * 仕様作成／更新が必要なとき、デザイナーをアサイン

トレーサビリティ
* チャットで議論を行った場合、チケットにリンクを貼ってトレース可能にしておく
