### ISSUE TITLE
スケジュール設定のたたき台設定

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#8]
**目的/課題**

- スケジュールが遅延すること
- 結合テストで想定以上のバグが出ること

**対策**

- 遅延すること前提で適切なバッファを設けること
- 実装、レビュー、マージの品質の向上を図る

**やること**

- そもそもスケジュールを遵守することの重要性を記載
- どれくらいのバッファをどうやって設けるべきか検討の上、明記する
- 開発速度と品質は表裏一体であることの説明
- 品質を向上させる仕組みについては、別ページで解説する
- PMがスケジュールを設定する際に気をつけるべきことを説明
- エンジニアがスケジュールを守るために気をつけるべきことを説明

**Comment by nambaseiichi-pentagon** [comment]
開発スケジュールの立て方イメージ（作業用スプシ）
https://docs.google.com/spreadsheets/d/1buV7Zhh_w30TjhOR2QBV1jkNzeIH3HG7nLn82fmX4oQ/edit#gid=0
