### ISSUE TITLE
予定工数入力のたたき台作成

### ISSUE THREAD

**Issue by ymmtshny** [pentagon-tokyo/ptg-quality#9]
現状予定工数をバックログに記入するような運用をしていない
=> 記入していないことによるそもそもの問題点を議論して明確にする。

**Comment by shintykt** [comment]
## なぜやるのか
https://github.com/pentagon-tokyo/ptg-quality/issues/25#issuecomment-1608640762

## 予定工数の見積もり方
- 以下を参考にタスクを洗い出す
  - https://github.com/pentagon-tokyo/ptg-quality/issues/11#issuecomment-1619382980
- PMの見積もりレビューを受ける
  - エンジニアが工数ブレのリスクがあるタスクについてPMに報告
